/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	float a;
	float b;
	char sign;
};
typedef struct numbers numbers;

struct numbers1 {
	float aa;
	float bb;
	char sign;
};
typedef struct numbers1 numbers1;

#define CALCULATOR_PROG 0x23451111
#define CALCULATOR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  float * add_1(numbers *, CLIENT *);
extern  float * add_1_svc(numbers *, struct svc_req *);
#define sub 2
extern  float * sub_1(numbers *, CLIENT *);
extern  float * sub_1_svc(numbers *, struct svc_req *);
#define mul 3
extern  float * mul_1(numbers *, CLIENT *);
extern  float * mul_1_svc(numbers *, struct svc_req *);
#define div 4
extern  float * div_1(numbers *, CLIENT *);
extern  float * div_1_svc(numbers *, struct svc_req *);
extern int calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  float * add_1();
extern  float * add_1_svc();
#define sub 2
extern  float * sub_1();
extern  float * sub_1_svc();
#define mul 3
extern  float * mul_1();
extern  float * mul_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculator_prog_1_freeresult ();
#endif /* K&R C */
#define CALCULATOR_VERS1 2

#if defined(__STDC__) || defined(__cplusplus)
extern  float * add_2(numbers1 *, CLIENT *);
extern  float * add_2_svc(numbers1 *, struct svc_req *);
extern  float * sub_2(numbers1 *, CLIENT *);
extern  float * sub_2_svc(numbers1 *, struct svc_req *);
extern  float * mul_2(numbers1 *, CLIENT *);
extern  float * mul_2_svc(numbers1 *, struct svc_req *);
extern  float * div_2(numbers1 *, CLIENT *);
extern  float * div_2_svc(numbers1 *, struct svc_req *);
extern int calculator_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  float * add_2();
extern  float * add_2_svc();
extern  float * sub_2();
extern  float * sub_2_svc();
extern  float * mul_2();
extern  float * mul_2_svc();
extern  float * div_2();
extern  float * div_2_svc();
extern int calculator_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_numbers1 (XDR *, numbers1*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_numbers1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
